version: '3'
services:
  skills-service:
    image: skilltree/skills-service:2.10.0
    # public.ecr.aws/bchewy/skilltree:latest --> on ECR
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROPS=spring.datasource.url=jdbc:postgresql://postgres:5432/skills,spring.datasource.username=skills,spring.datasource.password=skillsPassword
      - JAVA_OPTS=-Xmx512m -Xms256m
      - LOG_LEVEL=DEBUG
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-network

  postgres:
    image: postgres
    # public.ecr.aws/bchewy/skilltree:postgres --> on ECR
    environment:
      - POSTGRES_USER=skills
      - POSTGRES_PASSWORD=skillsPassword
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
