name: Deploy Flask to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/sustainable-singapore/backend
          git pull git@github.com:bchewy/sustainable-singapore.git main
          pip3 install -r requirements.txt
          pkill -f gunicorn || true  # It's okay if this fails
          nohup gunicorn -b 0.0.0.0:8888 app:app > gunicorn.log 2>&1 &
          sleep 5  # Give Gunicorn some time to start
          cat gunicorn.log  # Output the log for debugging
